language: go

go:
  - tip

services:
  - docker

script:
  - go get ./...
  - go test -v ./...
  - go vet ./...

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      cd checkup ;
      ls ;
      ./build.sh ;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      docker push smancke/insantus ;
    fi